### ISSUE TITLE
Please remove usages of branch property from manifests

### ISSUE THREAD

**Issue by bbhtt** [flathub/org.purei.Play#235]
https://github.com/flathub/org.purei.Play/blob/7bdaa958faf4182309c991586be56c02529bba35/org.purei.Play.yaml#L54

should be tag or commit or tag+commit

**Comment by jpd002** [comment]
I've made the change here: https://github.com/flathub/org.purei.Play/commit/548fff8207fe45515be23486453c3412e640ca24.
Do I also need to disable the auto updater by adding `disable-external-data-checker` in `flathub.json`?

**Comment by bbhtt** [comment]
No that is enough. 

You can add a x-checker para under it so that it updates whenever there is a new tag.
